# Generated by Django 5.1.5 on 2025-01-30 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booklib', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
